- task: CmdLine@2
  displayName: Deploy website
  inputs:
    script: |
      rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@<PUBLIC-IP>:/var/www/html/
      ssh -o StrictHostKeyChecking=no ubuntu@65.0.230.85 "sudo systemctl restart nginx"
